### PR TITLE
entities/enemies: fixed strange enemy behavior

### LINKED ISSUE #25: entities/enemies: strange enemy spawn behavior
Sometimes enemies spawn in the ground when one of the top corners don't have collision.

### PR DESCRIPTION
**Pull request by NikolayZahariev**
Fixes #25 

Fixed the issue where enemies sometimes spawn between two tiles that
were very close together. The issue arose from the tilemap itself: there
was a small invisible gap in between the two tiles where the enemy could
spawn.

### CODE REVIEW

File: src/main/java/scrublords/states/LevelOne.java [hunk 1]
```diff
@@ -37,7 +37,7 @@ public LevelOne() {
     public void init() {
         tileMap = new TileMap(30);
         tileMap.tileLoading.loadTiles("/tilesets/grasstileset.gif");
-        tileMap.mapLoading.loadMap("/maps/level1-1.map");
+        tileMap.mapLoading.loadMap("/maps/level1-map.map");
```
Comment (denisdimitrov) [inline src/main/java/scrublords/states/LevelOne.java]: level1-map.map sounds wrong, think of something else.
